galaxy_info:
  namespace: ruddhibhagat 
  role_name: nginx
  author: Ruddhi Bhagat
  description: Install and configure Nginx web server
  company: Atyeti
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
